FROM php:8.4-fpm

# Instalar dependências do sistema e extensões PHP
RUN apt-get update && apt-get install -y     git     curl     libpng-dev     libonig-dev     libxml2-dev     zip     unzip     libzip-dev     && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Corrigir erro do Git
RUN git config --global --add safe.directory /var/www

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configurar diretório de trabalho
WORKDIR /var/www

EXPOSE 9000
CMD ["php-fpm"]
