# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/minhamania.net
cert = /etc/letsencrypt/live/minhamania.net/cert.pem
privkey = /etc/letsencrypt/live/minhamania.net/privkey.pem
chain = /etc/letsencrypt/live/minhamania.net/chain.pem
fullchain = /etc/letsencrypt/live/minhamania.net/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d481512bb6f5463ef88005d529d97adc
authenticator = webroot
webroot_path = /var/www,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
minhamania.net = /var/www
www.minhamania.net = /var/www
